# error_handling.yml
retries:
  max_attempts: 3
  backoff_factor: 2
  initial_delay: 5

error_routing:
  network_errors:
    retry: true
    alert_threshold: 5
    cleanup_required: false
  
  pdf_processing_errors:
    retry: true
    max_attempts: 2
    cleanup_required: true
  
  database_errors:
    retry: false
    alert_immediate: true
    require_manual_intervention: true